In [4]:
import numpy as np
import pandas as pd
data=pd.read_csv("echallan_daily_data.csv")
print(data.info())


<class 'pandas.DataFrame'>
RangeIndex: 4061 entries, 0 to 4060
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             4061 non-null   str  
 1   totalChallan     4061 non-null   int64
 2   disposedChallan  4061 non-null   int64
 3   pendingChallan   4061 non-null   int64
 4   pendingAmount    4061 non-null   int64
 5   disposedAmount   4061 non-null   int64
 6   totalAmount      4061 non-null   int64
 7   pendingCourt     4061 non-null   int64
 8   disposedCourt    4061 non-null   int64
 9   totalCourt       4061 non-null   int64
dtypes: int64(9), str(1)
memory usage: 317.4 KB
None


In [33]:
df=data.describe()

                             date   totalChallan  disposedChallan  \
count                        4061    4061.000000      4061.000000   
mean   2020-07-23 14:15:16.621521  102564.295986     39190.895100   
min           2015-01-01 00:00:00      10.000000         6.000000   
25%           2017-10-12 00:00:00    1864.000000      1032.000000   
50%           2020-07-24 00:00:00  104931.000000     47012.000000   
75%           2023-05-05 00:00:00  174420.000000     67133.000000   
max           2026-02-13 00:00:00  332710.000000     96645.000000   
std                           NaN   94274.309905     30766.668065   

       pendingChallan  pendingAmount  disposedAmount   totalAmount  \
count     4061.000000   4.061000e+03    4.061000e+03  4.061000e+03   
mean     63373.400886   9.998178e+07    5.655994e+07  1.565417e+08   
min          3.000000   2.040000e+04    6.700000e+03  5.440000e+04   
25%       1131.000000   1.765850e+06    5.127580e+06  7.183220e+06   
50%      53038.000000   5.54

In [9]:
data['date']=pd.to_datetime(data['date'])
print(data.head(5))
print(data.isnull().sum())

date               0
totalChallan       0
disposedChallan    0
pendingChallan     0
pendingAmount      0
disposedAmount     0
totalAmount        0
pendingCourt       0
disposedCourt      0
totalCourt         0
dtype: int64


In [13]:
print(data.shape)
print(data["disposedAmount"].duplicated().sum()) # No Duplicates if date is , else if amount may there's


(4061, 10)
17


In [27]:
data['year']=data['date'].dt.year
data.loc[(data['year']<2020),"Free Kardo"]= 0
data.loc[(data['year']>2020),"Free Kardo"]= 1
print((data['Free Kardo']==0).sum())


1825


In [35]:
print((data['pendingChallan']<53038.000000).sum())

2030


In [37]:
print((data['totalChallan']>174420).cumsum())


0          0
1          0
2          0
3          0
4          0
        ... 
4056    1012
4057    1013
4058    1014
4059    1015
4060    1015
Name: totalChallan, Length: 4061, dtype: int64


In [49]:
data['disposed ratio']=data['disposedAmount']/data['totalChallan']
print(data.head(5))

        date  totalChallan  disposedChallan  pendingChallan  pendingAmount  \
0 2015-01-01           120               29              91         588600   
1 2015-01-02           162               39             123         663350   
2 2015-01-03           122               34              88         596900   
3 2015-01-04           116               27              89         967350   
4 2015-01-05           162               28             134         877654   

   disposedAmount  totalAmount  pendingCourt  disposedCourt  totalCourt  year  \
0          116860       705460             1              0           1  2015   
1          281425       944775             1              1           2  2015   
2          286950       883850             4              1           5  2015   
3          301600      1268950             3              2           5  2015   
4          103000       980654             2              0           2  2015   

   month  day  Free Kardo  disposed ratio  


In [51]:
data['Collection Rate']=data['disposedAmount']/data['totalAmount']
print(data.head(5))

        date  totalChallan  disposedChallan  pendingChallan  pendingAmount  \
0 2015-01-01           120               29              91         588600   
1 2015-01-02           162               39             123         663350   
2 2015-01-03           122               34              88         596900   
3 2015-01-04           116               27              89         967350   
4 2015-01-05           162               28             134         877654   

   disposedAmount  totalAmount  pendingCourt  disposedCourt  totalCourt  year  \
0          116860       705460             1              0           1  2015   
1          281425       944775             1              1           2  2015   
2          286950       883850             4              1           5  2015   
3          301600      1268950             3              2           5  2015   
4          103000       980654             2              0           2  2015   

   month  day  Free Kardo  disposed ratio  C

In [55]:
data['avg_fine'] = data['totalAmount'] / data['totalChallan']

print(data.corr())


                     date  totalChallan  disposedChallan  pendingChallan  \
date             1.000000      0.953749         0.875483        0.911675   
totalChallan     0.953749      1.000000         0.872643        0.976059   
disposedChallan  0.875483      0.872643         1.000000        0.745531   
pendingChallan   0.911675      0.976059         0.745531        1.000000   
pendingAmount    0.860001      0.924891         0.645220        0.974846   
disposedAmount   0.670876      0.664607         0.707092        0.592075   
totalAmount      0.892044      0.938644         0.743436        0.949871   
pendingCourt     0.865379      0.924831         0.791166        0.909763   
disposedCourt    0.684016      0.657796         0.903362        0.495367   
totalCourt       0.881454      0.932510         0.841938        0.897630   
year             0.995895      0.950973         0.874032        0.908532   
month            0.060118      0.045306         0.030506        0.048243   
day         

In [57]:
data['pending_ratio']=data['pendingChallan']/data['disposedChallan']
print(data.head(5))

        date  totalChallan  disposedChallan  pendingChallan  pendingAmount  \
0 2015-01-01           120               29              91         588600   
1 2015-01-02           162               39             123         663350   
2 2015-01-03           122               34              88         596900   
3 2015-01-04           116               27              89         967350   
4 2015-01-05           162               28             134         877654   

   disposedAmount  totalAmount  pendingCourt  disposedCourt  totalCourt  year  \
0          116860       705460             1              0           1  2015   
1          281425       944775             1              1           2  2015   
2          286950       883850             4              1           5  2015   
3          301600      1268950             3              2           5  2015   
4          103000       980654             2              0           2  2015   

   month  day  Free Kardo  disposed ratio  C

In [58]:
data['Cumulative_challan']=data['pendingChallan'].cumsum()
print(data.head(5))

        date  totalChallan  disposedChallan  pendingChallan  pendingAmount  \
0 2015-01-01           120               29              91         588600   
1 2015-01-02           162               39             123         663350   
2 2015-01-03           122               34              88         596900   
3 2015-01-04           116               27              89         967350   
4 2015-01-05           162               28             134         877654   

   disposedAmount  totalAmount  pendingCourt  disposedCourt  totalCourt  year  \
0          116860       705460             1              0           1  2015   
1          281425       944775             1              1           2  2015   
2          286950       883850             4              1           5  2015   
3          301600      1268950             3              2           5  2015   
4          103000       980654             2              0           2  2015   

   month  day  Free Kardo  disposed ratio  C

In [66]:
data['Court ratio']=100* data['totalCourt']/data['totalChallan']
print((data['Court ratio']>50).sum())

691


In [67]:
data['court_disposal_rate'] = data['disposedCourt'] / data['totalCourt']

print(data.head(5))


        date  totalChallan  disposedChallan  pendingChallan  pendingAmount  \
0 2015-01-01           120               29              91         588600   
1 2015-01-02           162               39             123         663350   
2 2015-01-03           122               34              88         596900   
3 2015-01-04           116               27              89         967350   
4 2015-01-05           162               28             134         877654   

   disposedAmount  totalAmount  pendingCourt  disposedCourt  totalCourt  ...  \
0          116860       705460             1              0           1  ...   
1          281425       944775             1              1           2  ...   
2          286950       883850             4              1           5  ...   
3          301600      1268950             3              2           5  ...   
4          103000       980654             2              0           2  ...   

   month  day  Free Kardo  disposed ratio  Collect

In [71]:
print(data.corr())

                         date  totalChallan  disposedChallan  pendingChallan  \
date                 1.000000      0.953749         0.875483        0.911675   
totalChallan         0.953749      1.000000         0.872643        0.976059   
disposedChallan      0.875483      0.872643         1.000000        0.745531   
pendingChallan       0.911675      0.976059         0.745531        1.000000   
pendingAmount        0.860001      0.924891         0.645220        0.974846   
disposedAmount       0.670876      0.664607         0.707092        0.592075   
totalAmount          0.892044      0.938644         0.743436        0.949871   
pendingCourt         0.865379      0.924831         0.791166        0.909763   
disposedCourt        0.684016      0.657796         0.903362        0.495367   
totalCourt           0.881454      0.932510         0.841938        0.897630   
year                 0.995895      0.950973         0.874032        0.908532   
month                0.060118      0.045

In [74]:
corr_matrix = np.corrcoef(data[['totalChallan',
                               'pendingChallan',
                               'totalAmount',
                               'totalCourt']].T)
print(corr_matrix)

[[1.         0.97605928 0.93864377 0.93251047]
 [0.97605928 1.         0.94987145 0.89763037]
 [0.93864377 0.94987145 1.         0.87108318]
 [0.93251047 0.89763037 0.87108318 1.        ]]


In [77]:
data['growth_rate'] = data['totalChallan'].pct_change() * 100
print(data['growth_rate'].head(10))


0          NaN
1    35.000000
2   -24.691358
3    -4.918033
4    39.655172
5   -35.802469
6     3.846154
7    56.481481
8   -18.934911
9   -21.167883
Name: growth_rate, dtype: float64


In [82]:
mean = np.mean(data['totalChallan'])
std = np.std(data['totalChallan'])

outliers = data[np.abs(data['totalChallan'] - mean) > 3*std]
print(outliers)


Empty DataFrame
Columns: [date, totalChallan, disposedChallan, pendingChallan, pendingAmount, disposedAmount, totalAmount, pendingCourt, disposedCourt, totalCourt, year, month, day, Free Kardo, disposed ratio, Collection Rate, avg_fine, pending_ratio, Cumulative_challan, Court ratio, court_disposal_rate, growth_rate]
Index: []

[0 rows x 22 columns]


In [86]:

summary = {
    "Total Challans": data['totalChallan'].sum(),
    "Total Revenue": data['totalAmount'].sum(),
    "Avg Daily Challan": data['totalChallan'].mean(),
    "Max Revenue Day": data['totalAmount'].max()
}
print(summary)

{'Total Challans': np.int64(416513606), 'Total Revenue': np.int64(635715945397), 'Avg Daily Challan': np.float64(102564.29598621029), 'Max Revenue Day': np.int64(2147021053)}
